---
name: Verify clock source
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - '*.c'
      - '*.h'
      - 'test/*.c'
      - 'test/*.h'
      - 'CMakeLists.txt'
      - '.github/workflows/verify-clock-source.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    name: Run test
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 12
          platform: x86
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.29.1'
      - name: Generate CMake project
        run: |
          mkdir build-test
          cmake -S . -D TEST=true -B build-test
      - name: Run wifi test
        run: cmake --build build-test --target wifi-test
      - name: Run clock test
        run: cmake --build build-test --target clock-test
      - name: Run led test
        run: cmake --build build-test --target led-test
  build:
    name: Build binary
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Install gcc-avr
        shell: bash
        run: sudo apt update && sudo apt install avr-libc gcc-avr
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.29.1'
      - name: Generate CMake project
        run: |
          mkdir build
          cmake -S . -B build
      - name: Build binary
        run: cmake --build build --target nixie-tube-clock
